---

#install files for webserver
- hosts: localhost
  vars_files:
  - secrets.yml

  tasks:
  - name: unzip sql dump
    unarchive:
        src: /home/ubuntu/lastresort/mydbdump.zip
        dest: /home/ubuntu/
        remote_src: true
        
  - name: Login into db and import table
    become: true
    mysql_db:
        login_host: sqldbforweb.cuc0twrqljlf.us-west-2.rds.amazonaws.com
        login_user: foo
        login_password: "{{ db_password }}"
        state: import
        name: mydb
        target: /home/ubuntu/mydbdump
